# pod-with-env.yaml
apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: lab06
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_USER
      value: wordpress
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_PASSWORD
      value: wordpress
    - name: MYSQL_ROOT_PASSWORD
      value: wordpress
    ports:
    - containerPort: 3306

